---
title: "Differential Expression using edgeR"
---

Last week we talked about Experimental Design. This week we're going to apply that knowledge to finding *differential expressed* genes or transcripts - finding those genes or transcripts that are expressed differently between groups in our experimental design.

That is, in general, are there genes for the samples in group A that have different counts than the samples in group B?

We'll Explore the `edgeR` package as one method to find differentially expressed genes. There is also the `DESeq2` package. 

:::{.callout-note}
## Am I doing this right?

If you are new to differential expression, it is worth talking with the Bioinformatics Core about your experimental design and how to set up your model matrix and contrasts.

You did consult with them about the experimental design of your experiment before you sent the samples to be processed?
:::

## Count Data is Discrete Data

What does it mean when we say a set of samples is differentially expressed when we are using count data?


:::{.callout-note}
## What about Single Cell Data?

Single cell data actually uses a similar approach to discover differentially expressed genes: the *pseudo-bulk* approach. That is, counts for like cells are treated like a single bulk RNA sample. Then the pseudo-bulk samples can be tested for differential expression much like we're going to do.
:::

## The General Differential Expression Workflow

```{mermaid}
A[Reading in Data] --> B
B[Annotation] --> C
C[Filtering and Normalization] --> D
D[Data Exploration] --> E
E[Design Matrix] --> F
F[Dispersion Estimation] --> G
G[Differential Expression] --> H
H[Annotation and Gene Set Analysis]
G --> I[Clustering and Visualization]
G --> J[Pathway and Network Analysis]
```

## What groups are we going to compare?


## Making a `DEGlist` Object

We can make a `DEGlist` object from our `SummarizedExperiment` object using []:

```{r}


```

## Commands Used in `edgeR` package

|Procedure|Command|
|---------|-------|
|Filtering|

## Data Filtering in `edgeR`

- We need to filter out those genes with low expression (low count number) before we run analysis. Alternatively, we can select genes to test by using Coefficient of Variation to find the most variable genes.


## Data Normalization in `edgeR`

One of the things we need to account for is library size of our samples. Experimentally, there is variability in the number of reads across samples. 

## Two group comparison



## Multiple Groups

In general, we want to use a Generalized Linear Model to discover differences between groups.

```{mermaid}
graph TD
  A["ANOVA\n(across all groups)"] --> B["Contrasts\n(between groups)"]
```

One thing to keep in mind is that unless we know which group comparisons we want to focus on, we first have to do the ANOVA (analysis of variance) test to see if there are *any* differences among all groups.

Only then can we move on to individual comparisons and discover differentially expressed genes for each group comparison. 

## Multiple Groups, Multiple Factors


## Take Home Points

- We need to filter out those genes with low expression (low count number) before we run analysis. Alternatively, we can select genes to test by using Coefficient of Variation to find the most variable genes.
- Count Data must be normalized by the library size to compare across samples.
- We model data using distributions, and use those models to find expression differences.
- `edgeR` and `DESeq2` are complementary approaches. Results from one method may be different than the other.
