---
title: "Bioconductor for Genomics"
format: html
---

This course will introduce you to the basic data structures and genomic data analysis in Bioconductor. Specifically, we will focus on the basics of RNAseq analysis, including differential expression, annotation, and gene set analysis. We will also focus on loading data and metadata into data structures such as `SummarizedExperiment`. By the end of this course, you should be familiar with a basic RNAseq analysis workflow utilizing RNAseq count data. 

Please note that this course requires the [Intro to R](https://hutchdatascience.org/Intro_to_R) course as a prerequisite, or the equivalent course. Please note that this course does not cover RNAseq workflows such as MultiQC and alignment. 

## Learning Objectives

- **Explain** and **Utilize** Bioconductor data structures such as `SummarizedExperiment` to integrate metadata and assay data in your analysis
- **Explore**, **QC**, and **clean** a RNAseq dataset
- **Utilize** Differential Expression analysis on an RNAseq dataset using Bioconductor Packages
- **Identify** and **Annotate** Gene Sets for downstream analysis
- **Load** data from RNAseq experiments into Bioconductor

```{mermaid}
graph TD
A[Reading in Data] --> B
B[Metadata] --> C
subgraph DESeq2
C[Data Exploration] --> D
D[Review Experiment Design] --> E
end
E[Filtering and Normalization] --> F
F[Dispersion Estimation] --> G
G[Differential Expression]
G --> H[Annotation and Gene Set Analysis]
G --> I[Clustering and Visualization]
G --> J[Pathway and Network Analysis]
classDef box fill:#DDD
class DESeq2 box
```

## Course Outline

|Week|Topic|Video|Office Hours|
|----|-----|-----|------------|
|Week 0| [Concepts of RNA sequencing](00_concepts.html) | | |
|Week 1| [Bioconductor Data Structures / What you need to know about S4 classes / `SummarizedExperiment`](01_introduction.html)| | |
|Week 2| [Experimental Design / QC / Visualization](02_week2.html)| | |
|Week 3| [Differential Expression](03-differential-expression.html) | | |
|Week 4| Gene sets and annotation| | |
|Week 5| Installing Bioconductor Packages / Loading Data into Bioconductor Data Structures| | |
|Week 6| Wrap up / Running Bioconductor at FH / Using fHR| | |

## Acknowledgements

This course is derived from the following sources:

- [RNA-seqn analysis with Bioconductor](https://github.com/carpentries-incubator/bioc-rnaseq/tree/main)